services:
  db:
    container_name: mongo
    image: mongo:8.0.9
    restart: on-failure
    # use the named volume we declare below
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: stg-api
    depends_on:
      - db
    restart: always
    build: ../FHNW-SQL-Training-Game-API
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stg-api
      - JWT_SECRET=FHNW_2021
      - FROM_SENDER=${FROM_SENDER}
      - POSTMARK_API_KEY=${POSTMARK_API_KEY}
      - PORT=3001
      - IO_URL=${IO_URL}
    ports:
      - "3001:3001"

  frontend:
    container_name: stg-frontend
    depends_on:
      - api
    restart: always
    build:
      context: .
      args:
        API_URL: ${API_URL}
    ports:
      - "80:80"
      - "3000:3000"

# Declare the named volume here
volumes:
  mongo-data:
